# Generated by Django 5.2.5 on 2025-09-02 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exam",
            name="questions",
        ),
        migrations.RemoveField(
            model_name="question",
            name="correct_option",
        ),
        migrations.RemoveField(
            model_name="question",
            name="option_a",
        ),
        migrations.RemoveField(
            model_name="question",
            name="option_b",
        ),
        migrations.RemoveField(
            model_name="question",
            name="option_c",
        ),
        migrations.RemoveField(
            model_name="question",
            name="option_d",
        ),
        migrations.AddField(
            model_name="question",
            name="exam",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="exams.exam",
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="exam",
            name="duration",
            field=models.IntegerField(default=10, help_text="Duration in minutes"),
        ),
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="exams.question",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserExamResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField()),
                ("taken_at", models.DateTimeField(auto_now_add=True)),
                (
                    "exam",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exams.exam",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="UserExam",
        ),
    ]
